import type { AppProps } from "next/app";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/font-awesome/css/all.css";
import "@/styles/icomoon/style.css";
import "@/styles/custom-stlye.css";
import "@/styles/custom.css";
import "@/styles/globals.css";
import "@/styles/ci/style.css";

import type { ReactElement, ReactNode } from "react";
import type { NextPage } from "next";
import { ApolloProvider } from "@apollo/client";
import client from "../../apollo-client/connector";
import { SessionProvider } from "next-auth/react";
import { RecoilRoot } from "recoil";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

const App: any = ({
  Component,
  pageProps: { session, ...pageProps },
}: AppPropsWithLayout) => {
  const getLayout = Component.getLayout ?? ((page) => page);
  return getLayout(
    <>
      <Head>
        <title>Bigbang Organizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;300;400;500;600;700;900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      {/* <SessionProvider session={session}> */}
      <ApolloProvider client={client}>
        <RecoilRoot>
          <Component {...pageProps} />
        </RecoilRoot>
      </ApolloProvider>
      {/* </SessionProvider> */}
    </>
  );
};

export default App;
