export interface iEvent {
  id?: number,
  uid?: string,
  name?: string,
  description?: string,
  image_url?: string,
  room_event_uid?: string,
  verse_uid?: string,
  ref_type?: string,
  ref_uid?: string,
  room_link?: string,
  json_url?: string,
  is_active?: string,
  start_at?: string,
  expired_at?: string,
  created_at?: Date,
  updated_at?: Date,
  deleted_at?: Date,
}