version: "3.8"
services:
  frontend:
    image: node:16-alpine3.12
    restart: always
    build: .
    ports:
      - "3000:3000"
    # environment:
    #   PORT: 3000
    # labels:
    #   caddy: market.bluewolfnft.com
    #   caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy

networks:
  caddy:
    external: true
